# Generated by Django 6.0.3 on 2026-08-07 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election_statistics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("division_number", models.IntegerField(unique=True)),
            ],
            options={
                "verbose_name": "Подразделение",
                "verbose_name_plural": "Подразделения",
            },
        ),
        migrations.RemoveField(
            model_name="stuff",
            name="PEC_address",
        ),
        migrations.RemoveField(
            model_name="stuff",
            name="PEC_district",
        ),
        migrations.RemoveField(
            model_name="stuff",
            name="PEC_district_number",
        ),
        migrations.RemoveField(
            model_name="stuff",
            name="PEC_number",
        ),
        migrations.AddField(
            model_name="stuff",
            name="division",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="election_statistics.division",
            ),
        ),
        migrations.CreateModel(
            name="PECs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PEC_number", models.IntegerField()),
                ("PEC_address", models.CharField()),
                ("PEC_district_number", models.IntegerField()),
                (
                    "PEC_district",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="election_statistics.districts",
                    ),
                ),
            ],
            options={
                "verbose_name": "УИК",
                "verbose_name_plural": "УИКи",
            },
        ),
        migrations.AddField(
            model_name="stuff",
            name="PEC",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="election_statistics.pecs",
            ),
        ),
    ]
