# Generated by Django 6.0.3 on 2026-08-10 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election_statistics", "0002_division_remove_stuff_pec_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stuff",
            name="voting_pec",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stuff",
            name="voting_pec_uvz",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stuff",
            name="voting_rev",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Voters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voting_rev", models.BooleanField(default=False)),
                ("voting_pec", models.BooleanField(default=False)),
                ("voting_pec_uvz", models.BooleanField(default=False)),
                ("voting_date", models.DateTimeField(auto_now=True)),
                (
                    "emp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="election_statistics.stuff",
                    ),
                ),
            ],
        ),
    ]
