# Generated by Django 6.0.3 on 2026-08-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election_statistics", "0003_stuff_voting_pec_stuff_voting_pec_uvz_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voters",
            name="voting_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
