# Generated by Django 6.0.3 on 2026-08-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("election_statistics", "0004_alter_voters_voting_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="voters",
            options={"verbose_name": "Голос", "verbose_name_plural": "Голоса"},
        ),
    ]
