# Generated by Django 6.0.2 on 2026-08-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election_statistics", "0005_alter_voters_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tab_number",
                    models.CharField(max_length=20, unique=True, verbose_name="Таб№"),
                ),
                (
                    "department",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Подразделение"
                    ),
                ),
                ("surname", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Отчество"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Должность"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Категория"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=100, verbose_name="Регион"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Город"),
                ),
                (
                    "street",
                    models.CharField(blank=True, max_length=150, verbose_name="Улица"),
                ),
                (
                    "house",
                    models.CharField(blank=True, max_length=20, verbose_name="Дом"),
                ),
                (
                    "uik",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, verbose_name="УИК"
                    ),
                ),
                (
                    "uik_address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Адрес УИК"
                    ),
                ),
                (
                    "district",
                    models.CharField(blank=True, max_length=100, verbose_name="Район"),
                ),
                (
                    "okrug",
                    models.CharField(blank=True, max_length=10, verbose_name="Округ"),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[("deg", "ДЭГ"), ("uik", "УИК"), ("uvz", "УИК-УВЗ")],
                        db_index=True,
                        max_length=3,
                        verbose_name="Способ голосования",
                    ),
                ),
                (
                    "voted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Проголосовал"
                    ),
                ),
                (
                    "voted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время отметки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["surname", "name", "patronymic"],
            },
        ),
        migrations.RemoveField(
            model_name="stuff",
            name="city",
        ),
        migrations.RemoveField(
            model_name="pecs",
            name="PEC_district",
        ),
        migrations.RemoveField(
            model_name="stuff",
            name="division",
        ),
        migrations.RemoveField(
            model_name="stuff",
            name="PEC",
        ),
        migrations.RemoveField(
            model_name="stuff",
            name="region",
        ),
        migrations.RemoveField(
            model_name="stuff",
            name="street",
        ),
        migrations.RemoveField(
            model_name="voters",
            name="emp",
        ),
        migrations.DeleteModel(
            name="Cities",
        ),
        migrations.DeleteModel(
            name="Districts",
        ),
        migrations.DeleteModel(
            name="Division",
        ),
        migrations.DeleteModel(
            name="PECs",
        ),
        migrations.DeleteModel(
            name="Regions",
        ),
        migrations.DeleteModel(
            name="Streets",
        ),
        migrations.DeleteModel(
            name="Stuff",
        ),
        migrations.DeleteModel(
            name="Voters",
        ),
    ]
