# Generated by Django 6.0.2 on 2026-08-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "election_statistics",
            "0006_employee_remove_stuff_city_remove_pecs_pec_district_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="voted_method",
            field=models.CharField(
                blank=True,
                choices=[("deg", "ДЭГ"), ("uik", "УИК"), ("uvz", "УИК-УВЗ")],
                db_index=True,
                max_length=3,
                verbose_name="Где проголосовал",
            ),
        ),
    ]
