# Generated by Django 6.0.2 on 2026-08-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election_statistics", "0007_employee_voted_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Номер цеха"
                    ),
                ),
                (
                    "production",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Производство"
                    ),
                ),
            ],
            options={
                "verbose_name": "Цех",
                "verbose_name_plural": "Цеха",
                "ordering": ["production", "number"],
            },
        ),
    ]
