# Generated by Django 6.0.2 on 2026-08-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election_statistics", "0008_workshop"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Workshop",
        ),
        migrations.AddField(
            model_name="employee",
            name="production",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, verbose_name="Производство"
            ),
        ),
    ]
