# Generated by Django 6.0.2 on 2026-08-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election_statistics", "0009_delete_workshop_employee_production"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deg", "ДЭГ"),
                    ("uik", "УИК"),
                    ("uvz", "УИК-УВЗ"),
                    ("u19", "УИК-19"),
                ],
                db_index=True,
                max_length=3,
                verbose_name="Способ голосования",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="voted_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deg", "ДЭГ"),
                    ("uik", "УИК"),
                    ("uvz", "УИК-УВЗ"),
                    ("u19", "УИК-19"),
                ],
                db_index=True,
                max_length=3,
                verbose_name="Где проголосовал",
            ),
        ),
    ]
