# Generated by Django 6.0.2 on 2026-08-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "election_statistics",
            "0010_alter_employee_method_alter_employee_voted_method",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="detached",
            field=models.BooleanField(default=False, verbose_name="Открепился"),
        ),
        migrations.AddField(
            model_name="employee",
            name="not_going",
            field=models.BooleanField(default=False, verbose_name="Не пойдет"),
        ),
    ]
