# Generated by Django 6.0.2 on 2026-08-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election_statistics", "0011_employee_detached_employee_not_going"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="service",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, verbose_name="Служба"
            ),
        ),
    ]
