# Generated by Django 6.0.2 on 2026-09-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election_statistics", "0012_employee_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="mark",
            field=models.BooleanField(default=False, verbose_name="Отметка"),
        ),
    ]
