# Generated by Django 6.0.2 on 2026-09-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election_statistics", "0013_employee_mark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="mark",
        ),
        migrations.AddField(
            model_name="employee",
            name="mark_deg",
            field=models.BooleanField(default=False, verbose_name="Регистрация на ДЭГ"),
        ),
        migrations.AddField(
            model_name="employee",
            name="mark_uvz",
            field=models.BooleanField(
                default=False, verbose_name="Регистрация на УИК-УВЗ"
            ),
        ),
    ]
