# Generated by Django 6.0.2 on 2026-09-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election_statistics", "0014_remove_employee_mark_employee_mark_deg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="voted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Проголосал"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="voted_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deg", "ДЭГ"),
                    ("uik", "УИК"),
                    ("uvz", "УИК-УВЗ"),
                    ("u19", "УИК-19"),
                ],
                db_index=True,
                max_length=3,
                verbose_name="Где голосовал",
            ),
        ),
    ]
