# Generated by Django 6.0.3 on 2026-09-03 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_statistics', '0015_alter_employee_voted_alter_employee_voted_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=64, null=True, verbose_name='API ключ')),
                ('patronymic', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('is_fired', models.BooleanField(default=False, verbose_name='Уволен?')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('sync_error', models.TextField(blank=True, verbose_name='Ошибка последней синхронизации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
