# Generated by Django 6.0.2 on 2026-09-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "election_statistics",
            "0015_alter_employee_voted_alter_employee_voted_method",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="absence",
            field=models.BooleanField(default=False, verbose_name="Отсутствие по УП"),
        ),
    ]
