# Generated by Django 6.0.2 on 2026-09-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election_statistics", "0016_employee_absence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="okrug",
            field=models.CharField(
                blank=True, db_index=True, max_length=10, verbose_name="Округ"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="voted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Проголосовал"
            ),
        ),
    ]
