# Generated by Django 6.0.3 on 2026-09-04 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_statistics', '0016_profile'),
        ('election_statistics', '0017_alter_employee_okrug_alter_employee_voted'),
    ]

    operations = [
    ]
