# Generated by Django 6.0.3 on 2026-09-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_statistics', '0018_merge_20260904_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_number', models.CharField(max_length=20, unique=True, verbose_name='Таб№')),
                ('department', models.CharField(db_index=True, max_length=50, verbose_name='Подразделение')),
                ('production', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Производство')),
                ('service', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Служба')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=150, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=20, verbose_name='Дом')),
                ('uik', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='УИК')),
                ('uik_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес УИК')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Район')),
                ('okrug', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='Округ')),
                ('method', models.CharField(blank=True, choices=[('deg', 'ДЭГ'), ('uik', 'УИК'), ('uvz', 'УИК-УВЗ'), ('u19', 'УИК-19')], db_index=True, max_length=3, verbose_name='Способ голосования')),
                ('voted', models.BooleanField(db_index=True, default=False, verbose_name='Проголосовал')),
                ('voted_method', models.CharField(blank=True, choices=[('deg', 'ДЭГ'), ('uik', 'УИК'), ('uvz', 'УИК-УВЗ'), ('u19', 'УИК-19')], db_index=True, max_length=3, verbose_name='Где голосовал')),
                ('voted_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отметки')),
                ('detached', models.BooleanField(default=False, verbose_name='Открепился')),
                ('not_going', models.BooleanField(default=False, verbose_name='Не пойдет')),
                ('mark_uvz', models.BooleanField(default=False, verbose_name='Регистрация на УИК-УВЗ')),
                ('mark_deg', models.BooleanField(default=False, verbose_name='Регистрация на ДЭГ')),
                ('absence', models.BooleanField(default=False, verbose_name='Отсутствие по УП')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['surname', 'name', 'patronymic'],
            },
        ),
    ]
