# Generated by Django 6.0.2 on 2026-09-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("election_statistics", "0018_merge_20260904_0934"),
        ("election_statistics", "0019_employeearchive"),
    ]

    operations = []
