# Generated by Django 6.0.2 on 2026-09-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "election_statistics",
            "0020_merge_0018_merge_20260904_0934_0019_employeearchive",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeearchive",
            options={
                "ordering": ["surname", "name", "patronymic"],
                "verbose_name": "Сотрудник(уволен)",
                "verbose_name_plural": "Сотрудники(уволенные)",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="id_uik",
            field=models.IntegerField(blank=True, null=True, verbose_name="ID УИК"),
        ),
        migrations.AddField(
            model_name="employee",
            name="uik_tik",
            field=models.IntegerField(blank=True, null=True, verbose_name="УИК ТИК"),
        ),
    ]
