# Generated by Django 6.0.2 on 2026-09-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "election_statistics",
            "0021_alter_employeearchive_options_employee_id_uik_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="proxy_vote",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="Голосование через ответственного",
            ),
        ),
        migrations.AddField(
            model_name="employeearchive",
            name="proxy_vote",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="Голосование через ответственного",
            ),
        ),
    ]
