# Generated by Django 6.0.2 on 2026-09-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_statistics', '0023_alter_employeearchive_options_employeearchive_id_uik_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeearchive',
            options={'ordering': ['surname', 'name', 'patronymic'], 'verbose_name': 'Сотрудник(уволен)', 'verbose_name_plural': 'Сотрудники(уволенные)'},
        ),
    ]
